In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.84247567  0.07181843 -0.0888164   1.98458938  0.10373907]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.84247567  0.07181843 -0.0888164   1.98458938  0.10373907]


In [5]:
print(np.dot(a, a.T))

4.672168295433644


In [6]:
a = np.random.randn(5, 1)
print(a)

[[1.13356936]
 [1.28929052]
 [1.46427244]
 [1.28012621]
 [0.46540326]]


In [7]:
print(a.T)

[[1.13356936 1.28929052 1.46427244 1.28012621 0.46540326]]


In [8]:
print(np.dot(a, a.T))

[[1.28497948 1.46150023 1.65985437 1.45111184 0.52756687]
 [1.46150023 1.66227005 1.88787259 1.65045458 0.60004001]
 [1.65985437 1.88787259 2.14409379 1.87445353 0.68147716]
 [1.45111184 1.65045458 1.87445353 1.6387231  0.5957749 ]
 [0.52756687 0.60004001 0.68147716 0.5957749  0.21660019]]
